# Generated by Django 5.2.6 on 2025-09-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitationAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listcitation',
            old_name='Auteur',
            new_name='auteur',
        ),
    ]
